version: "3.8"

services:
  backend:
    image: onealwaseem/thegirlypoppers-backend:latest
    restart: always
    environment:
      PORT:  ${PORT}
      CONNECTION_URL: ${CONNECTION_URL}
      JWT_SECRET:  ${JWT_SECRET}
      EMAIL_USER:  ${EMAIL_USER}
      EMAIL_PASS:  ${EMAIL_PASS}
      CLOUDINARY_CLOUD_NAME:  ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY:  ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET:  ${CLOUDINARY_API_SECRET}
      CLOUDINARY_URL:  ${CLOUDINARY_URL}
      EMAIL_SERVICE:  ${EMAIL_SERVICE}
      GOOGLE_CLIENT_ID:  ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET:  ${GOOGLE_CLIENT_SECRET}
      FRONTEND_URL:  ${FRONTEND_URL}
    ports:
      - "3018:3018"

  frontend:
    image: onealwaseem/thegirlypoppers-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3017:3017"