version: "3.8"

services:
  backend:
    image: onealwaseem/finalproject-backend:latest
    restart: always
    environment:
      PORT: 3000
      CONNECTION_URL: mongodb://e2425-wads-l4bcg2:motis6u2@localhost:27018/e2425-wads-l4bcg2?authSource=e2425-wads-l4bcg2
      EMAIL_USER: cottoneightservice@gmail.com
      EMAIL_PASSWORD: dcoe wiwm hrbz wwwe
      CLOUDINARY_CLOUD_NAME: dfe7uyntq
      CLOUDINARY_API_KEY: 892865934638977
      CLOUDINARY_API_SECRET: QoHBalqcQPTHWBJ1VQ88kv4_eOw
      CLOUDINARY_URL: cloudinary://892865934638977:QoHBalqcQPTHWBJ1VQ88kv4_eOw@dfe7uyntq
      EMAIL_SERVICE: gmail
      GOOGLE_CLIENT_ID: 310044493415-q6tk0ko1vemi8js1ht290pop4ircqgfg.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
      FRONTEND_URL: http://localhost:5173
    ports:
      - "3018:3018"

  frontend:
    image: onealwaseem/finalproject-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3017:3017"